### ISSUE TITLE
Handle :left and :right suffixes

### ISSUE THREAD

**Issue by daniel-j-h** [mapbox/osrm-tag-rewriter#10]
There are some `exit_to:left`, `exit_to:right` and `ref:left`, `ref:right` tags we have to handle.
The edge case we stumbled upon are sub-exits, e.g. with `ref=1 A; 1B` + `ref:left=1A` + `ref:right=1B`:

https://www.openstreetmap.org/edit#map=18/37.26047/-121.85779

![map0](https://user-images.githubusercontent.com/527241/28408882-280b88b4-6d39-11e7-98fd-b99bbf81cab7.png)

Currently we only re-write the `ref` tag which is terrible here: both ways splitting off will get the `1A; 1B` as exits which is plain wrong. We have a few options here:
- parse `:left` and `:right` suffices and try to associate them with the correct way
- don't re-write `ref` tags if there are also `:left` and `:right` tags on the motorway junction node
- just re-tag these edge cases with `junction:ref` already in the data

It looks like there are roughly 700 `ref:left` and `ref:right` tags out in the wild and 570 of those are in combination with the `ref` tag. So we screw up most of them currently.

(Same applies to `exit_to`, `exit_to:left`, `exit_to:right` of which there are not that many luckily)

@1ec5 @srividyacb opinions here?

**Comment by 1ec5** [comment]
Previously: https://github.com/mapbox/osrm-tag-rewriter/issues/7#issuecomment-313763364

If it's feasible to manually copy ref:left and ref:right on junction nodes to junction:ref on link ways in OSM, that would be great. In that case, we'd want to avoid rewriting when a :left or :right is present, because sometimes there's only a ref:left or ref:right but not both. (Sometimes one side has no number.)

Otherwise, if we can't fix this at the data level, then we'd have to figure out which is left and which is right. Hopefully there aren't any edge cases with more than two link ways branching out from the junction node. (If I recall correctly, this was a strong argument in favor of deprecating exit_to back in the day.)

**Comment by daniel-j-h** [comment]
Urgh sorry for not correctly reading and understanding the implications of the issue you raised before.

I will disable re-writing for now if we see a motorway junction with `ref` and (`ref:left` or `ref:right`).

**Comment by daniel-j-h** [comment]
This got a hotfix in https://github.com/mapbox/osrm-tag-rewriter/pull/11.

**Comment by srividyacb** [comment]
👏 @daniel-j-h
